[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-builders"
version = "0.1.0"
requires-python = ">=3.9"
description = "Input/Target builders for SeisAI"
dependencies = ["numpy", "torch", "seisai-dataset>=0.1.0"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["seisai_builders*"]
