CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_A0.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_A1.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_A2.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_B1.yaml
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_B2.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_B3.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_C1.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_C2.yaml
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_C3.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_D1.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_D2.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_D3.yaml
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_D3_noaa.yaml &
CUDA_VISIBLE_DEVICES=0 python cli/run_blindtrace_train.py --config proc/mae/configs/prestage_D3_t5.yaml
