CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_huber_masked_d1.yaml &
CUDA_VISIBLE_DEVICES=1 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_masked.yaml
CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_plus_fxmag_all_w005.yaml &
CUDA_VISIBLE_DEVICES=1 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_plus_fxmag_all_w01.yaml
CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_plus_fxmag_all_w02.yaml &
CUDA_VISIBLE_DEVICES=1 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_plus_mse_all_w005.yaml
CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_plus_mse_all_w01.yaml &
CUDA_VISIBLE_DEVICES=1 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_l1_plus_mse_all_w02.yaml
CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_mse_masked.yaml &
CUDA_VISIBLE_DEVICES=1 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_shift4_masked.yaml
CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_shift8_masked.yaml &
CUDA_VISIBLE_DEVICES=1 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_shift_robust_l1_s2.yaml
CUDA_VISIBLE_DEVICES=0 python examples/examples_train_blindtrace.py --config proc/mae/configs/loss_v2_shift_robust_l1_s4.yaml
