coarse:
  input_mode: global_anchor_resize
dataset:
  use_header_cache: true
  verbose: true
  progress: true
  primary_keys:
  - ffid
  waveform_mode: eager
  train_endian: big
  infer_endian: big
fbgate:
  apply_on: any
  min_pick_ratio: 0.3
  verbose: false
transform:
  trace_len: 256
  time_len: 2048
  standardize_eps: 1.0e-08
trace_anchor:
  gap_ratio: 5.0
  min_gap_m: null
  train_mode: random
  infer_mode: center
norm_refs:
  time_ref_sec: 20.0
  offset_ref_m: 2000.0
model:
  backbone: resnet18
  pretrained: false
  in_chans: 3
  out_chans: 1
  pre_stages: 3
  pre_stage_strides:
  - - 1
    - 2
  - - 1
    - 1
  - - 1
    - 2
  pre_stage_channels:
  - 16
  - 32
  - 32
  pre_stage_kernels:
  - 3
  - 3
paths:
  segy_files: /workspace/proc/fbpick/site54/oof/fold_lists/folds/fold05/train_sgy.txt
  fb_files: /workspace/proc/fbpick/site54/oof/fold_lists/folds/fold05/train_fb.txt
  infer_segy_files: /workspace/proc/fbpick/site54/oof/fold_lists/folds/fold05/inner_valid_sgy.txt
  infer_fb_files: /workspace/proc/fbpick/site54/oof/fold_lists/folds/fold05/inner_valid_fb.txt
  out_dir: /workspace/proc/fbpick/site54/oof/runs/baseline_physical_center/fold05/01_coarse_train
train:
  seed: 0
  epochs: 30
  samples_per_epoch: 256
  batch_size: 4
  num_workers: 0
  max_norm: 1.0
  use_amp: true
  lr: 0.0001
  weight_decay: 0.0
  fb_sigma_ms: 10.0
  print_freq: 10
infer:
  seed: 0
  batch_size: 1
  num_workers: 0
  max_batches: 8
vis:
  n: 5
  out_subdir: vis
ckpt:
  save_best_only: true
  metric: infer_loss
  mode: min
