# packages/seis-dataset/pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-dataset"
version = "0.1.0"
description = "SEG-Y gather dataset & augmentation toolkit"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
  "numpy",
  "scipy",
  "torch",
  "segyio",
]

# augment 機能はオプション依存にして transforms へ片方向依存（循環回避）
[project.optional-dependencies]
augment = ["seis-transforms>=0.1.0"]

[tool.setuptools.packages.find]
where = ["src"]         
include = ["seisds*"]
