[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-engine"
version = "0.1.0"
description = "Training/inference loops, logging, and (optional) distributed utils for SeisAI"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
  "numpy",
  "torch",
  "tqdm",
  "seisai-data>=0.2.0",
  "seisai-transforms>=0.1.0",
  "seisai-models>=0.1.0",
]

# Hydra/OMEGACONFを使うなら有効化
# [project.optional-dependencies]
# hydra = ["hydra-core>=1.3", "omegaconf>=2.3"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["seisai_engine*"]